sudo: false
language: scala

scala:
  - 2.12.4
  - 2.11.12

jdk:
  - oraclejdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "ChristopherDavenport/linebacker" && sbt ++$TRAVIS_SCALA_VERSION publish
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "ChristopherDavenport/linebacker" && test $TRAVIS_SCALA_VERSION == "2.12.4" && sbt microsite/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt